apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-simple-react
spec:
  environments:
    - name: dev
      authorization:
      - role: RadixAppAdmin
        groups:
        - "g_radix_platform_user"
    - name: prod
      authorization:
      - role: RadixAppAdmin
        groups:
        - "g_radix_platform_user"
  components:
    - name: app
      src: "."
      ports:
       - 80
      public: true
